name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    # Run weekly (* is a special character in YAML, so quote the string)
    - cron:  '0 0 * * 0'

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        compiler: [g++, clang++]

    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies (ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt install libboost-test-dev
    - name: Install Dependencies (macos)
      if: matrix.os == 'macos-latest'
      run: |
        brew install boost
        brew install gcc
        echo $PATH
    - name: Compile (${{ matrix.compiler }})
      env:
        CXX: ${{ matrix.compiler }}
      run: make --directory tests
    - name: Test
      run: tests/test_revdoor
